# Generated by Django 2.1.2 on 2018-11-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.CharField(max_length=20)),
                ('PTJob', models.CharField(max_length=2)),
                ('Loan', models.CharField(max_length=2)),
                ('Aid', models.CharField(max_length=2)),
                ('Scholorship', models.CharField(max_length=2)),
                ('Year', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.CharField(max_length=20)),
                ('School', models.TextField()),
                ('Major', models.TextField()),
                ('BirthYear', models.CharField(max_length=5)),
                ('Country', models.TextField()),
                ('National', models.TextField()),
                ('Entrance', models.CharField(max_length=20)),
                ('Province', models.TextField()),
                ('Gender', models.CharField(max_length=5)),
                ('State', models.TextField()),
                ('Type', models.TextField()),
                ('Year', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.CharField(max_length=20)),
                ('BookID', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=20)),
                ('OperType', models.CharField(max_length=5)),
                ('StuType', models.CharField(max_length=5)),
                ('Department', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.CharField(max_length=20)),
                ('DateTime', models.CharField(max_length=30)),
                ('Cost', models.CharField(max_length=10)),
                ('POS', models.CharField(max_length=5)),
                ('Meal', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.CharField(max_length=20)),
                ('DateTime', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.CharField(max_length=20)),
                ('School', models.TextField()),
                ('FinanceType', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HosBX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.CharField(max_length=20)),
                ('SchoolHos', models.TextField()),
                ('Cause', models.TextField()),
                ('DateTime', models.CharField(max_length=30)),
                ('BX', models.CharField(max_length=10)),
                ('OriginCost', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HosReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.CharField(max_length=20)),
                ('SchoolHos', models.TextField()),
                ('CostType', models.TextField()),
                ('DateTime', models.CharField(max_length=30)),
                ('Department', models.TextField()),
                ('RegCost', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='HosTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.CharField(max_length=20)),
                ('SchoolHos', models.TextField()),
                ('DateTime', models.CharField(max_length=30)),
                ('Hospital', models.TextField()),
                ('Department', models.TextField()),
                ('SchDepart', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.CharField(max_length=20)),
                ('DateTime', models.CharField(max_length=30)),
                ('Gate', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Moral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.CharField(max_length=20)),
                ('Level1', models.CharField(max_length=2)),
                ('Level2', models.CharField(max_length=5)),
                ('ItemID', models.CharField(max_length=8)),
                ('ItemName', models.TextField()),
                ('Semester', models.TextField()),
                ('Prize', models.TextField()),
                ('State', models.CharField(max_length=2)),
                ('PrizeType', models.TextField()),
                ('ActivityLevel', models.CharField(max_length=2)),
                ('Note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.CharField(max_length=20)),
                ('School', models.TextField()),
                ('Semester', models.CharField(max_length=10)),
                ('CourseNum', models.CharField(max_length=2)),
                ('Credits', models.CharField(max_length=2)),
                ('AveScore', models.CharField(max_length=10)),
                ('Lowest', models.CharField(max_length=10)),
                ('Highest', models.CharField(max_length=10)),
                ('Up90', models.CharField(max_length=2)),
                ('Up80', models.CharField(max_length=2)),
                ('Up70', models.CharField(max_length=2)),
                ('Up60', models.CharField(max_length=2)),
                ('Low60', models.CharField(max_length=2)),
                ('Num0', models.CharField(max_length=2)),
            ],
        ),
    ]
