# Generated by Django 2.1.2 on 2018-12-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_health_intervene'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('Name', models.TextField()),
                ('Password', models.CharField(max_length=20)),
                ('Job', models.TextField()),
                ('Department', models.TextField()),
                ('School', models.TextField()),
                ('Major', models.TextField()),
                ('Grade', models.TextField()),
                ('Reg', models.CharField(max_length=5)),
                ('Login', models.CharField(max_length=15)),
            ],
        ),
    ]
