# Generated by Django 2.1.2 on 2018-12-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Authority',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='register',
            name='Email',
            field=models.EmailField(default='1005178642@qq.com', max_length=254, unique=True),
        ),
    ]
