# Generated by Django 2.1.5 on 2019-02-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20181229_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterveneSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_state', models.CharField(max_length=10)),
                ('is_fail_exam', models.BooleanField()),
                ('body_health_state', models.TextField()),
                ('treatment_count', models.CharField(max_length=10)),
                ('moral', models.TextField()),
                ('suggestion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='moral',
            name='Grade',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='moral',
            name='School',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='score',
            name='Grade',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='basic',
            name='Gender',
            field=models.TextField(),
        ),
    ]
