# Generated by Django 2.1.5 on 2019-02-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190219_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='classNo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='lib',
            name='DateTime',
            field=models.DateTimeField(),
        ),
    ]
