# Generated by Django 2.1.2 on 2019-02-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190223_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='DateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lib',
            name='DateTime',
            field=models.DateTimeField(),
        ),
    ]
