# Generated by Django 2.1.2 on 2019-02-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190223_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='DateTime',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lib',
            name='DateTime',
            field=models.CharField(max_length=30),
        ),
    ]
