# Generated by Django 2.1.2 on 2019-02-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20190223_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosbx',
            name='DateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hosreg',
            name='DateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hostrans',
            name='DateTime',
            field=models.DateTimeField(),
        ),
    ]
