# Generated by Django 2.1.2 on 2019-02-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20190223_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostrans',
            name='DateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hostrans',
            name='SchDepart',
            field=models.TextField(),
        ),
    ]
