# Generated by Django 2.1.2 on 2019-03-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190223_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.CharField(max_length=20)),
                ('Score', models.CharField(max_length=10)),
            ],
        ),
    ]
