# Generated by Django 2.1.2 on 2019-04-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_predscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='Grade',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='health',
            name='basic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Basic', to_field='StuID'),
        ),
        migrations.AddField(
            model_name='score',
            name='basic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Basic', to_field='StuID'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='StuID',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='Year',
            field=models.TextField(max_length=5),
        ),
    ]
