# Generated by Django 2.2 on 2019-04-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20190408_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='basic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Basic', to_field='StuID'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='DateTime',
            field=models.DateTimeField(),
        ),
    ]
