# Generated by Django 2.2 on 2019-04-09 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20190408_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosreg',
            name='basic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Basic', to_field='StuID'),
        ),
    ]
