# Generated by Django 2.2 on 2019-04-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_card_basic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='DateTime',
            field=models.DateTimeField(),
        ),
    ]
