# Generated by Django 2.2 on 2019-04-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20190409_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='DateTime',
            field=models.CharField(max_length=20),
        ),
    ]
